name: manage-azure-policy-594e821f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'manifests/policy/policies/Kubernetes_cluster_containers_requested_cpu_should_exceed_beta_0d8ec0cd-2fe6-4f59-ac27-4eb68e883b2d/**'
#      - .github/workflows/manage-azure-policy-594e821f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_594e821f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          manifests/policy/policies/Kubernetes_cluster_containers_requested_cpu_should_exceed_beta_0d8ec0cd-2fe6-4f59-ac27-4eb68e883b2d/**
